/*
 * Hospital Equipment Management API
 *
 * Storage Equipment management for hospital
 *
 * API version: 1.0.0
 * Contact: xskrabakf@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage_equipment

import (
	"github.com/gin-gonic/gin"
)

type EquipmentManagementAPI interface {


    // CreateEquipment Post /api/equipment
    // Add new equipment 
     CreateEquipment(c *gin.Context)

    // DeleteEquipment Delete /api/equipment/:equipmentId
    // Delete equipment 
     DeleteEquipment(c *gin.Context)

    // GetAllEquipment Get /api/equipment
    // Get all equipment 
     GetAllEquipment(c *gin.Context)

    // GetEquipmentById Get /api/equipment/:equipmentId
    // Get equipment by ID 
     GetEquipmentById(c *gin.Context)

    // UpdateEquipment Put /api/equipment/:equipmentId
    // Update equipment 
     UpdateEquipment(c *gin.Context)

}