/*
 * Hospital Equipment Management API
 *
 * Storage Equipment management for hospital
 *
 * API version: 1.0.0
 * Contact: xskrabakf@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage_equipment

import (
	"github.com/gin-gonic/gin"
)

type EquipmentOrdersAPI interface {


    // CancelOrder Delete /api/orders/:orderId
    // Cancel order 
     CancelOrder(c *gin.Context)

    // CreateOrder Post /api/orders
    // Create a new equipment order 
     CreateOrder(c *gin.Context)

    // GetOrderById Get /api/orders/:orderId
    // Get order by ID 
     GetOrderById(c *gin.Context)

    // ListOrders Get /api/orders
    // List all orders 
     ListOrders(c *gin.Context)

    // UpdateStatus Put /api/orders/:orderId
    // Update order 
     UpdateStatus(c *gin.Context)

}