/*
 * Hospital Equipment Management API
 *
 * Storage Equipment management for hospital
 *
 * API version: 1.0.0
 * Contact: xskrabakf@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage_equipment

type EquipmentItem struct {

	Id string `json:"id"`

	// Name of the equipment
	Name string `json:"name"`

	// Serial number of the equipment
	SerialNumber string `json:"serialNumber"`

	// Manufacturer of the equipment
	Manufacturer string `json:"manufacturer"`

	// Model of the equipment
	Model string `json:"model,omitempty"`

	// Date when equipment was installed
	InstallationDate string `json:"installationDate"`

	// Location of the equipment in the hospital
	Location string `json:"location"`

	// Service interval in days
	ServiceInterval int32 `json:"serviceInterval,omitempty"`

	// Date of last service
	LastService string `json:"lastService,omitempty"`

	// Date of next scheduled service
	NextService string `json:"nextService,omitempty"`

	// Life expectancy in years
	LifeExpectancy int32 `json:"lifeExpectancy,omitempty"`

	Status string `json:"status,omitempty"`

	// Additional notes about the equipment
	Notes string `json:"notes,omitempty"`
}
