/*
 * Hospital Equipment Management API
 *
 * Storage Equipment management for hospital
 *
 * API version: 1.0.0
 * Contact: xskrabakf@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage_equipment

import (
	"time"
)

type Order struct {

	// Unique identifier for the order
	Id string `json:"id"`

	// List of equipment items requested in this order
	Items []OrderItem `json:"items"`

	// Name or ID of the staff member who created the order
	RequestedBy string `json:"requestedBy"`

	// Department that requested the equipment
	RequestorDepartment string `json:"requestorDepartment,omitempty"`

	// Current status of the order
	Status string `json:"status"`

	// Additional notes about the order
	Notes string `json:"notes,omitempty"`

	// Date and time when the order was created
	CreatedAt time.Time `json:"createdAt"`

	// Date and time when the order was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
