/*
 * Hospital Equipment Management API
 *
 * Storage Equipment management for hospital
 *
 * API version: 1.0.0
 * Contact: xskrabakf@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage_equipment

type EquipmentUpdate struct {

	// Name of the equipment
	Name string `json:"name,omitempty"`

	// Serial number of the equipment
	SerialNumber string `json:"serialNumber,omitempty"`

	// Manufacturer of the equipment
	Manufacturer string `json:"manufacturer,omitempty"`

	// Model of the equipment
	Model string `json:"model,omitempty"`

	// Location of the equipment in the hospital
	Location string `json:"location,omitempty"`

	// Service interval in days
	ServiceInterval int32 `json:"serviceInterval,omitempty"`

	// Date of last service
	LastService string `json:"lastService,omitempty"`

	// Life expectancy in years
	LifeExpectancy int32 `json:"lifeExpectancy,omitempty"`

	Status string `json:"status,omitempty"`

	// Additional notes about the equipment
	Notes string `json:"notes,omitempty"`
}
