/*
 * Hospital Equipment Management API
 *
 * Storage Equipment management for hospital
 *
 * API version: 1.0.0
 * Contact: xskrabakf@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage_equipment

type OrderCreate struct {

	// List of equipment items to be ordered
	Items []OrderItem `json:"items"`

	// Name or ID of the staff member creating the order
	RequestedBy string `json:"requestedBy"`

	// Department ordering the equipment
	RequestorDepartment string `json:"requestorDepartment,omitempty"`

	// Additional notes about the order request
	Notes string `json:"notes,omitempty"`
}
