kind: Service
apiVersion: v1
metadata:
  name: steq-storage-equipment
spec:
  selector:
    pod: steq-storage-equipment-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port