# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and Publish WebAPI Container Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v1*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  {} # allow manually trigger workflow

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Go version from go.mod
      id: get_go_version
      run: echo "go_version=$(grep -m1 'go ' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.get_go_version.outputs.go_version }}

    - name: Build
      run: go build -v ./cmd/storage-equipment-api-service

    - name: Test
      run: go test -v ./...
